### ISSUE TITLE
Install for laravel 5.4

### ISSUE THREAD

**Issue by RushNetMx** [gamerwalt/laramultidbtenant#7]
Hello! I'm using an app with laravel 5.4, is there a way I could use it with this version? Thanks

**Comment by gamerwalt** [comment]
Yes you should be able to use it.

Adewoyin Olawale Bañez
Winnipeg, Manitoba,
Canada

gamerwalt@gmail.com
gamerwalt@hotmail.com

**Comment by RushNetMx** [comment]
I use the example for the package, I create a users table in the tenant database, How can I make that the users created in that database logging? Thanks!

**Comment by gamerwalt** [comment]
Sorry, I don't understand what you mean.

**Comment by wemersonjanuario** [comment]
@RushNetMx have you seen this demo example? https://github.com/gamerwalt/TodoMultitenantDemo. Maybe can help you
